version: '3'
services:
  api:
    image: comunidadevs-api:latest
    ports:
      - '${PORT_API}:${PORT_API}'
  mongo:
    image: mongo
    restart: always
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'

volumes:
  mongodata:
